args <- commandArgs(TRUE)
library(Rling)
a <- as.numeric(args[1])
b <- as.numeric(args[2])
c <- as.numeric(args[3])
d <- as.numeric(args[4])
LL <- LL.collostr(a, b, c, d)
aExp <- (a + b) * (a + c) / (a + b + c + d)
LL1 <- ifelse(a < aExp, -LL, LL)
print(LL1)
